[tool.poetry]
name = "solace"
version = "0.1.13"
description = "A modern microframework for building REST APIs in Python"
authors = ["Dan Sikes <dansikes7@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Werkzeug = "^2.0.0"
munch = "^2.5.0"
typer = "^0.3.2"
Mako = "^1.1.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
solace = 'solace.main:cli'
