[tool.poetry]
name = "tqatest"
version = "0.0.14"
description = "Backend module for testing project"
authors = ["QA"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.7"
fastapi = {extras = ["testclient"], version = "^0.68.1"}
uvicorn = "^0.11.1"
pydantic = "^1.3"
requests = "^2.22.0"
loguru = "^0.4.0"
pytest = "^6.2.4"
joblib = "^1.0.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
black = {version = "^19.10b0", allow-prereleases = true}
autopep8 = "^1.4.4"
ipdb = "^0.12.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
