[tool.poetry]
name = "bomb-boom"
version = "1.41.0-alpha.0"
description = "Bomb package"
authors = ["Nikita Barinov <diadorer@yandex.ru>"]

packages = [
    { include = "bomb", from = "." },
]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
