[tool.poetry]
name = "jam-pypi"
version = "0.0.5"
description = "Tesing repo for publish via ci"
authors = ["qsh.27 <qsh.zh27@gmail.com>"]
readme = "README.md"
keywords = ["jam", "pypi", "testing"]
packages = [
    {include = "jam_pypi"},
]

[tool.poetry.dependencies]
python = ">=3.7,<3.10"
numpy = "^1.21.2"

[tool.poetry.dev-dependencies]
pre-commit = "^2.13.0"
black = "^21.5b1"
isort = "^5.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
