[tool.poetry]
name = "convert_to_queryset"
version = "0.1.6"
description = "library for convert list,tuple and dictionary into queryset"
authors = ["deepak <info.deepakpatidar@gmail.com>"]
repository = 'https://github.com/DeepakDarkiee/convert_to_queryset.git'
readme = 'README.md'
keywords = ['convert','list','queryset']


[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
